[NMI,ACC] = evaluation('C:\Users\95850\Desktop\实验二\output\football_alinkjaccard.txt ', 'C:\Users\95850\Desktop\实验二\dataset\football_gd.txt ', 12);
str = sprintf("football_alinkjaccard:\nNMI: %.4f,ACC: %.4f\n",NMI,ACC);
disp(str);
[NMI,ACC] = evaluation('C:\Users\95850\Desktop\实验二\output\football_girvannewman.txt ', 'C:\Users\95850\Desktop\实验二\dataset\football_gd.txt ', 12);
str = sprintf("football_girvannewman:\nNMI: %.4f,ACC: %.4f\n",NMI,ACC);
disp(str);
[NMI,ACC] = evaluation('C:\Users\95850\Desktop\实验二\output\football_rcut.txt ', 'C:\Users\95850\Desktop\实验二\dataset\football_gd.txt ', 12);
str = sprintf("football_rcut:\nNMI: %.4f,ACC: %.4f\n",NMI,ACC);
disp(str);
[NMI,ACC] = evaluation('C:\Users\95850\Desktop\实验二\output\football_ncut.txt ', 'C:\Users\95850\Desktop\实验二\dataset\football_gd.txt ', 12);
str = sprintf("football_ncut:\nNMI: %.4f,ACC: %.4f\n",NMI,ACC);
disp(str);
[NMI,ACC] = evaluation('C:\Users\95850\Desktop\实验二\output\football_modularity.txt ', 'C:\Users\95850\Desktop\实验二\dataset\football_gd.txt ', 12);
str = sprintf("football_modularity:\nNMI: %.4f,ACC: %.4f\n",NMI,ACC);
disp(str);

[NMI,ACC] = evaluation('C:\Users\95850\Desktop\实验二\output\polbooks_alinkjaccard.txt ', 'C:\Users\95850\Desktop\实验二\dataset\polbooks_gd.txt ', 3);
str = sprintf("polbooks_alinkjaccard:\nNMI: %.4f,ACC: %.4f\n",NMI,ACC);
disp(str);
[NMI,ACC] = evaluation('C:\Users\95850\Desktop\实验二\output\polbooks_girvannewman.txt ', 'C:\Users\95850\Desktop\实验二\dataset\polbooks_gd.txt ', 3);
str = sprintf("polbooks_girvannewman:\nNMI: %.4f,ACC: %.4f\n",NMI,ACC);
disp(str);
[NMI,ACC] = evaluation('C:\Users\95850\Desktop\实验二\output\polbooks_rcut.txt ', 'C:\Users\95850\Desktop\实验二\dataset\polbooks_gd.txt ', 3);
str = sprintf("polbooks_rcut:\nNMI: %.4f,ACC: %.4f\n",NMI,ACC);
disp(str);
[NMI,ACC] = evaluation('C:\Users\95850\Desktop\实验二\output\polbooks_ncut.txt ', 'C:\Users\95850\Desktop\实验二\dataset\polbooks_gd.txt ', 3);
str = sprintf("polbooks_ncut:\nNMI: %.4f,ACC: %.4f\n",NMI,ACC);
disp(str);
[NMI,ACC] = evaluation('C:\Users\95850\Desktop\实验二\output\polbooks_modularity.txt ', 'C:\Users\95850\Desktop\实验二\dataset\polbooks_gd.txt ', 3);
str = sprintf("polbooks_modularity:\nNMI: %.4f,ACC: %.4f\n",NMI,ACC);
disp(str);